spring:
  aop:
    proxy-target-class: true
  sleuth:
    feign:
      enabled: false
    sampler:
      percentage: 0.2
  zipkin:
    base-url: http://47.115.212.214:9411/
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 5000
    sentinel:
      master: mymaster
      nodes: 47.115.212.214:26379,47.115.212.214:26480,47.115.212.214:26581
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ServerListRefreshInterval: 1000
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetriesNextServer: 3
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
logging:
  config: classpath:logback/logback-spring.xml
